baseurl: https://blog.dreamonex.eu.org
languageCode: zh-cn
theme: hugo-theme-stack
paginate: 5
title: 点点晨曦 | DreamOneX's Blog

author:
   name: "DreamOneX"

frontmatter:
  lastmod: [":fileModTime", "lastmod"]

languages:
    en:
        languageName: English
        title: Dawn Light | DreamOneX's Blog
        weight: 2
    zh-cn:
        languageName: 中文
        title: 点点晨曦 | DreamOneX's Blog
        weight: 1

# Change it to your Disqus shortname before using
disqusShortname: hugo-theme-stack

# GA Tracking ID
googleAnalytics: G-10XR3FX2WN

# Theme i18n support
# Available values: ar, bn, ca, de, el, en, es, fr, hu, id, it, ja, ko, nl, pt-br, th, uk, zh-cn, zh-hk, zh-tw
DefaultContentLanguage: zh-cn

# Set hasCJKLanguage to true if DefaultContentLanguage is in [zh-cn ja ko]
# This will make .Summary and .WordCount behave correctly for CJK languages.
hasCJKLanguage: true

permalinks:
    post: /p/:year/:month/:slug/
    page: /page/:slug/

params:
    mainSections:
        - post
    featuredImageField: image
    rssFullContent: true
    favicon:

    footer:
        since: 2022
        customText:

    dateFormat:
        published: 2006-01-02
        lastUpdated: 2006-01-02 15:04 UTC

    sidebar:
        emoji: 🍥
        subtitle: 实践是检验真理的唯一标准
        avatar:
            enabled: true
            local: true
            src: img/avatar.png

    article:
        math: false
        toc: true
        readingTime: true
        license:
            enabled: true
            default: Licensed under CC BY-SA 4.0

    comments:
        enabled: true
        provider: utterances

        disqusjs:
            shortname:
            apiUrl:
            apiKey:
            admin:
            adminLabel:

        utterances:
            repo: "DreamOneX/DawnLight-source"
            issueTerm: pathname
            label: "💬✨comment"

        remark42:
            host:
            site:
            locale:

        vssue:
            platform:
            owner:
            repo:
            clientId:
            clientSecret:
            autoCreateIssue: false

        # Waline client configuration see: https://waline.js.org/en/reference/component.html
        waline:
            serverURL: 'https://dawn-light-comment-mxxft72z5-me-dreamonexeu.vercel.app/'
            lang: 'zh-CN'
            pageview:
            emoji:
                - https://unpkg.com/@waline/emojis@1.0.1/weibo
                - https://unpkg.com/@waline/emojis@1.0.1/bilibili
                - https://unpkg.com/@waline/emojis@1.0.1/tieba
                - https://unpkg.com/@waline/emojis@1.0.1/qq
                - https://unpkg.com/@waline/emojis@1.0.1/tw
            requiredMeta:
                - name
            locale:
                admin: Admin
                placeholder:

        twikoo:
            envId:
            region:
            path:
            lang:

        # See https://cactus.chat/docs/reference/web-client/#configuration for description of the various options
        cactus:
            defaultHomeserverUrl: "https://matrix.cactus.chat:8448"
            serverName: "cactus.chat"
            siteName: "" # You must insert a unique identifier here matching the one you registered (See https://cactus.chat/docs/getting-started/quick-start/#register-your-site)

        giscus:
            repo:
            repoID:
            category:
            categoryID:
            mapping:
            lightTheme:
            darkTheme:
            reactionsEnabled: 1
            emitMetadata: 0

        gitalk:
            owner: "DreamOneX"
            admin: "DreamOneX"
            repo: "DawnLight-source"
            clientID: "9fbb0eafb39e1350996f" #revoked
            clientSecret: "87d4994005d1a6b71885403d43f5d983599a3346"

        cusdis:
            host:
            id:
    widgets:
        homepage:
            - type: search
            - type: archives
              params:
                  limit: 5
            - type: categories
              params:
                  limit: 10
            - type: tag-cloud
              params:
                  limit: 10
        page:
            - type: toc

    opengraph:
        twitter:
            # Your Twitter username
            site:

            # Available values: summary, summary_large_image
            card: summary_large_image

    defaultImage:
        opengraph:
            enabled: false
            local: false
            src:

    colorScheme:
        # Display toggle
        toggle: true

        # Available values: auto, light, dark
        default: auto

    imageProcessing:
        cover:
            enabled: true
        content:
            enabled: true

### Custom menu
### See https://docs.stack.jimmycai.com/configuration/custom-menu.html
### To remove about, archive and search page menu item, remove `menu` field from their FrontMatter
menu:
    main: []

    social:
        - identifier: github
          name: GitHub
          url: https://github.com/DreamOneX
          params:
              icon: brand-github

        - identifier: twitter
          name: Twitter
          url: https://twitter.com/dreamonex1
          params:
              icon: brand-twitter

        - identifier: telegram
          name: Telegram
          url: https://t.me/dreamonex1
          params:
              icon: brand-telegram

        - identifier: email
          name: Email
          url: mailto:me@dreamonex.eu.org
          params:
              icon: mail

        - identifier: rss
          name: RSS
          #url: https://blog.dreamonex.eu.org/index.xml
          url: /post/feed.xml
          params:
              icon: rss

related:
    includeNewer: true
    threshold: 60
    toLower: false
    indices:
        - name: tags
          weight: 100

        - name: categories
          weight: 200

markup:
    goldmark:
        extensions:
            definitionList: true
            footnote: true
            linkify: true
            linkifyProtocol: https
            strikethrough: true
            table: true
            taskList: true
            typographer: true
            emoji: false
        parser:
            attribute:
                block: false
                title: true
            autoHeadingID: true
            # autoHeadingIDType: 'github'
        renderer:
            ## Set to true if you have HTML content inside Markdown
            unsafe: true
            hardWraps: false
    tableOfContents:
        endLevel: 4
        ordered: true
        startLevel: 1
    highlight:
        noClasses: false
        codeFences: true
        guessSyntax: true
        lineNoStart: 1
        lineNos: true
        lineNumbersInTable: true
        tabWidth: 4

outputFormats:
    RSS:
        mediatype: "application/rss"
        baseName: "feed"
